### ISSUE TITLE
at which point CI has  prisma generate results

### ISSUE THREAD

**Issue by vandriesh** [jacobparis/remix-nx-fly#4]
I've been trying to replicated your recipe to "bring" two remix app under nx roof

got stuck under  `nx run typechecking`

```bash
Error: app/models/note.server.ts(1,15): error TS2[30](https://github.com/vandriesh/dev-assist/actions/runs/4489434364/jobs/7895249729#step:6:32)5: Module '"@prisma/client"' has no exported member 'User'.
```

I've generated indie stac.

I guess the question - is locally we generated prisma schema using 
```json
{
...
"scripts": {
    ...,
    "setup": "prisma generate && prisma migrate deploy && prisma db seed",
    ...
}
...
}
```

but what about CI env - how to make typechecking pass if we didn't generated schema in the CI env?

Thank you.

**Comment by jacobparis** [comment]
Oh this is a bug! There's a weird "--if-affected" flag on the typecheck script in the workflow that makes it not find the real typecheck target, so the typechecks are just never running (and always returning green)

Running the setup script before the typecheck seems like the most straightforward solution here

```yml
- name: 🔎 Setup
        run: npx nx affected --base=$([[ ${{ github.ref == 'refs/heads/main'}} ]] && echo "origin/main~1" || echo "origin/main") --head=HEAD --target="setup" --parallel=3
        
- name: 🔎 Type check
        run: npx nx affected --base=$([[ ${{ github.ref == 'refs/heads/main'}} ]] && echo "origin/main~1" || echo "origin/main") --head=HEAD --target="typecheck" --if-affected --parallel=3  
```
